config/routes.rb
Dictionary::Application.routes.draw do
     resources :words do
	post 'search', :on => :collection
  end
  root to: "words#index"

end

app/models/word.rb
class Word < ActiveRecord::Base
	def initial
    # find a number at the start of the string if it exists
    m = self.name.match(/^\d+/)
    return m[0] if m
    # or return the first letter upcased otherwise
    return self.name.slice( 0, 1 ).upcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
    @letter= (params[:word])
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end
  def search
	  @words = Word.find( :all , :conditions => ["word LIKE ?", "#{params[:key]}"])
	  end
  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  #def create
    #@word = Word.new(word_params)

    #respond_to do |format|
      #if @word.save
        #format.html { redirect_to @word, notice: 'Word was successfully created.' }
        #format.json { render action: 'show', status: :created, location: @word }
      #else
        #format.html { render action: 'new' }
        #format.json { render json: @word.errors, status: :unprocessable_entity }
      #end
    #end
  #end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  #def update
    #respond_to do |format|
      #if @word.update(word_params)
        #format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        #format.json { head :no_content }
      #else
        #format.html { render action: 'edit' }
        #format.json { render json: @word.errors, status: :unprocessable_entity }
      #end
    #end
  #end

  # DELETE /words/1
  # DELETE /words/1.json
  #def destroy
    #@word.destroy
    #respond_to do |format|
      #format.html { redirect_to words_url }
      #format.json { head :no_content }
    #end
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:word, :wordtype, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dictionary</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/words.html.erb
<DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1-transitional.dtd"></DOCTYPE>
<html>
  <head>
    <title>Devils Dictionary</title>
    
      <%=stylesheet_link_tag  "/stylesheet/styles", :media => "all" %>
  </head>
  <body= "body">
 
      </div>
<div id="main">
    <%= yield  :layout%>
    </div><br/>
<p></p>

    </div>
  </div>
</body>
</html>
  </body>
</html>

app/views/words/-.erb
#<h1>Editing word</h1>

#<%= render 'form' %>

#<%= link_to 'Show', @word %> |
#<%= link_to 'Back', words_path %>

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :wordtype %><br>
    <%= f.text_field :wordtype %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
#<h1>Editing word</h1>

#<%= render 'form' %>

#<%= link_to 'Show', @word %> |
#<%= link_to 'Back', words_path %>
<td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td><td><%= link_to 'Edit', edit_word_path(word) %></td>

app/views/words/index.html.erb
<html>
<h3>Search</h3>
<form action ="words/search"  method="post">
<input  name="key"  type="input"/>
<input  value="Search" type="submit"/>
</form>
<br>
<h1>Listing words</h1>

  <%= link_to ('A'), words_path(:word => 'A') %>
  <%= link_to ('B'), words_path(:word => 'B') %>
  <%= link_to ('C'), words_path(:word => 'C') %>
  <%= link_to ('D'), words_path(:word => 'D') %>
  <%= link_to ('E'), words_path(:word => 'E') %>
  <%= link_to ('F'), words_path(:word => 'F') %>
  <%= link_to ('G'), words_path(:word => 'G') %>
  <%= link_to ('H'), words_path(:word => 'H') %>
  <%= link_to ('I'), words_path(:word => 'I') %>
  <%= link_to ('J'), words_path(:word => 'J') %>
  <%= link_to ('K'), words_path(:word => 'K') %>
  <%= link_to ('L'), words_path(:word => 'L') %>
  <%= link_to ('M'), words_path(:word => 'M') %>
  <%= link_to ('O'), words_path(:word => 'O') %>
  <%= link_to ('P'), words_path(:word => 'P') %>
  <%= link_to ('Q'), words_path(:word => 'Q') %>
  <%= link_to ('R'), words_path(:word => 'R') %>
  <%= link_to ('S'), words_path(:word => 'S') %>
  <%= link_to ('U'), words_path(:word => 'U') %>
  <%= link_to ('V'), words_path(:word => 'V') %>
  <%= link_to ('W'), words_path(:word => 'W') %>
  <%= link_to ('X'), words_path(:word => 'X') %>
  <%= link_to ('Y'), words_path(:word => 'Y') %>
  
<table>
  <thead>
    
  </thead>

  <tbody>
    <% @words.each do |word| %>
    <%if word.word.chars.first==@letter %>
    
      <tr>
        <td><%= word.word %></td>
        <td><%= word.wordtype %></td>
        <td><%= word.description %></td>
        <td><%= link_to 'Show', word %></td>
        
      </tr>
      <%else if @letter == nil %>
      <tr>
        <td><%= word.word %></td>
        <td><%= word.wordtype %></td>
        <td><%= word.description %></td>
        <td><%= link_to 'Show', word %></td>
      </tr>
    <% end %>
     <% end %>
      <% end %>
  </tbody>
</table>






</html>

app/views/words/lettersearch.html.erb
<h1>Search Results</h1>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th>Wordtype</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.word %></td>
        <td><%= word.wordtype %></td>
        <td><%= word.description %></td>
        <td><%= link_to 'Show', word %></td>
        
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/search.html.erb
<h1>Search Results</h1>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th>Wordtype</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @word.each do |word| %>
      <tr>
        <td><%= word.word %></td>
        <td><%= word.wordtype %></td>
        <td><%= word.description %></td>
        <td><%= link_to 'Show', word %></td>
        
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @word.word %>
</p>

<p>
  <strong>Wordtype:</strong>
  <%= @word.wordtype %>
</p>

<p>
  <strong>Description:</strong>
  <%= @word.description %>
</p>

<%= link_to 'Back', words_path %>
<!-- Start of Flickr Badge -->
<style type="text/css">
#flickr_badge_source_txt {padding:0; font: 11px Arial, Helvetica, Sans serif; color:#666666;}
#flickr_badge_icon {display:block !important; margin:0 !important; border: 1px solid rgb(0, 0, 0) !important;}
#flickr_icon_td {padding:0 5px 0 0 !important;}
.flickr_badge_image {text-align:center !important;}
.flickr_badge_image img {border: 1px solid black !important;}
#flickr_www {display:block; text-align:left; padding:0 10px 0 10px !important; font: 11px Arial, Helvetica, Sans serif !important; color:#3993ff !important;}
#flickr_badge_uber_wrapper a:hover,
#flickr_badge_uber_wrapper a:link,
#flickr_badge_uber_wrapper a:active,
#flickr_badge_uber_wrapper a:visited {text-decoration:none !important; background:inherit !important;color:#3993ff;}
#flickr_badge_wrapper {background-color:#ffffff;border: solid 1px #000000}
#flickr_badge_source {padding:0 !important; font: 11px Arial, Helvetica, Sans serif !important; color:#666666 !important;}
</style>
<table id="flickr_badge_uber_wrapper" cellpadding="0" cellspacing="10" border="0"><tr><td><a href="http://www.flickr.com" id="flickr_www">www.<strong style="color:#3993ff">flick<span style="color:#ff1c92">r</span></strong>.com</a><table cellpadding="0" cellspacing="10" border="0" id="flickr_badge_wrapper">
<tr>
<script type="text/javascript" src="http://www.flickr.com/badge_code_v2.gne?show_name=1&count=1&display=latest&size=t&layout=h&source=all_tag&tag=children&user=119573061%40N02"></script>
<td id="flickr_badge_source" valign="center" align="center">
<table cellpadding="0" cellspacing="0" border="0"><tr>
<td id="flickr_badge_source_txt">More <a href="http://www.flickr.com/photos/tags/children/">photos or video tagged with children</a> on Flickr</td>
</tr></table>
</td>
</tr>
</table>
</td></tr></table>
<!-- End of Flickr Badge -->